/* AUTO-GENERATED by scripts/fetch-portfolio-previews.mjs */
export const PORTFOLIO_PREVIEWS: Record<string, string[]> = {
  "https://dostavka-zpr.ru/": [
    "/portfolio-previews/dostavka-zpr-1.jpg",
    "/portfolio-previews/dostavka-zpr-2.jpg",
    "/portfolio-previews/dostavka-zpr-3.jpg"
  ],
  "https://krymresurs.ru/": [
    "/portfolio-previews/krymresurs-1.jpg",
    "/portfolio-previews/krymresurs-2.jpg"
  ],
  "https://sechat.ru/": [
    "/portfolio-previews/sechat-1.jpg",
    "/portfolio-previews/sechat-2.jpg",
    "/portfolio-previews/sechat-3.jpg"
  ],
  "https://mozgovnet.com/": [
    "/portfolio-previews/mozgovnet-1.jpg",
    "/portfolio-previews/mozgovnet-2.jpg",
    "/portfolio-previews/mozgovnet-3.jpg"
  ],
  "https://biznesmashin.ru/": [
    "/portfolio-previews/biznesmashin-1.jpg",
    "/portfolio-previews/biznesmashin-2.jpg"
  ],
  "https://windowcleaner.com/": [
    "/portfolio-previews/windowcleaner-1.jpg",
    "/portfolio-previews/windowcleaner-2.jpg",
    "/portfolio-previews/windowcleaner-3.jpg"
  ],
  "https://gratisiskolan.se/": [
    "/portfolio-previews/gratisiskolan-1.jpg",
    "/portfolio-previews/gratisiskolan-2.jpg",
    "/portfolio-previews/gratisiskolan-3.jpg"
  ],
  "https://microline.ua/": [
    "/portfolio-previews/microline-1.jpg",
    "/portfolio-previews/microline-2.jpg"
  ],
  "https://www.epik.com/": [
    "/portfolio-previews/epik-1.png"
  ]
};
